version: '3'
services:
  web:
    # Uncomment the next line to use a non-root user for all processes. Update the "remoteUser" property 
    # in devcontainer.json if you just want VS Code and its sub-processes to execute as the user. 
    # See https://aka.ms/vscode-remote/containers/non-root for details.
    #
    # user: node

    build: 
      context: .
      dockerfile: Dockerfile
      args:
        VARIANT: 12
        # On Linux, you may need to update USER_UID and USER_GID below if not your local UID is not 1000.
        USER_UID: 1000
        USER_GID: 1000
    
    volumes:
      - ..:/workspace:cached
      
    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity

    links:
      - db

  db:
    image: postgres
    restart: unless-stopped
    ports: 
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: pass
      POSTGRES_USER: user
      POSTGRES_DB: data
 
